# Generated by Django 5.0.3 on 2024-03-09 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_tag_product_image_producttag_product_tag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tag',
            new_name='tags',
        ),
    ]
