# Generated by Django 5.0.3 on 2024-03-09 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_tag_product_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='admin_user_id',
            new_name='admin_user',
        ),
    ]
