
class OrderStatusChoice:
    PENDING = 'PENDING'
    PAYMENT_SUCCESS = 'PAYMENT_SUCCESS'
    CANCELED = 'CANCELED'
    SUCCESS = 'SUCCESS'

    CHOICE_LIST = [
        (PENDING,PENDING),
        (PAYMENT_SUCCESS,PAYMENT_SUCCESS),
        (CANCELED,CANCELED),
        (SUCCESS,SUCCESS)
    ]
